# Site settings
title:          Yesid is learning about...
description:    "Minimal Jekyll theme for storytellers"
url:            "https://yesidbotero.github.io"

# Author
author:
  name:         Yesid Botero
  url:
  email:        yesidboterom@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
